# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tallakt-plcutil}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tallak Tveide"]
  s.date = %q{2010-10-12}
  s.description = %q{Ruby library for using Siemens and Intouch files}
  s.email = %q{tallak@tveide.net}
  s.executables = ["awlpp", "intouchpp", "pl7tointouch", "s7tointouch"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "LICENSE",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/awlpp",
     "bin/intouchpp",
     "bin/pl7tointouch",
     "bin/s7tointouch",
     "lib/tallakt-plcutil.rb",
     "lib/tallakt-plcutil/schneider/pl7_to_intouch_runner.rb",
     "lib/tallakt-plcutil/siemens/awl_pretty_print_runner.rb",
     "lib/tallakt-plcutil/siemens/awlfile.rb",
     "lib/tallakt-plcutil/siemens/sdffile.rb",
     "lib/tallakt-plcutil/siemens/step7_to_intouch_runner.rb",
     "lib/tallakt-plcutil/wonderware/intouch_pretty_print_runner.rb",
     "lib/tallakt-plcutil/wonderware/intouchfile.rb",
     "lib/tallakt-plcutil/wonderware/standard_sections.yaml",
     "script/console",
     "script/console.cmd",
     "script/destroy",
     "script/destroy.cmd",
     "script/generate",
     "script/generate.cmd",
     "tallakt-plcutil.gemspec",
     "test/helper.rb",
     "test/input_files/step7_v5.4/00000001.AWL",
     "test/input_files/step7_v5.4/S7_pro2.zip",
     "test/input_files/step7_v5.4/SYMLIST.DBF",
     "test/test_tallakt-plcutil.rb"
  ]
  s.homepage = %q{http://github.com/tallakt/plcutil}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby PLC file library}
  s.test_files = [
    "test/helper.rb",
     "test/test_tallakt-plcutil.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

